name: "Push Workflow"

on:
  push:
    branches:
    - "*"
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true


jobs:
  tf_deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0
      - name: install dependencies
        run: |
          npm install -g cdktf-cli@latest --force
          npm install --force
      - name: Config credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: CDKTF init
        run: |
          cdktf --app "npx ts-node stacks.ts" synth
          #STACKS=$(ls cdktf.out/stacks/)
          #for stack in $STACKS; do
            cdktf --app "npx ts-node stacks.ts" deploy "*" --auto-approve
          #done
        env:
          VPC_ID: ${{ secrets.VPC_ID }}
          STATE_BUCKET: ${{ secrets.BUCKET_NAME }}
          SUBNET: ${{ secrets.SUBNET_ID }}


